language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.3
    - android-25
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - ls -la /usr/local/android-sdk/licenses
  - chmod +x gradlew

script:
  - ./gradlew test --no-daemon
