language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-google-m2repository
  licenses:
    - 'android-sdk-.+'
    - 'google-gdk-.+'

before_install:
  - chmod +x gradlew

script:
  - ./gradlew test --no-daemon
